### ISSUE TITLE
Add user classes, based on time on hubben.

### ISSUE THREAD

**Issue by Rawa** [cthit/hubbIT-sniffer#7]
A user should have a user class, based on their time in hubben.

For example:

Score:
0-100 = Nollsmurf
200-500 = Baby smurf
....
9000+ = Gammelsmurf

Based on the userlevel the user should also recieve a corresponding class icon, which is displayed to the left of the username on the front page of hubbit. Possiobly a user could select an avatar based on what avatars he have recieved. E.g being a member of digit would give you access to the digit/didit smurf, etc..

**Comment by fridenmf** [comment]
@Rawa Is there a clear different to this instead of simple achievements for those score levels?

**Comment by Rawa** [comment]
@fridenmf Yes, a userclass clearly marks the users progress and should be displayed on the frontpage. Thus providing a rank, which an achievement clearly does not.

**Comment by lindskogen** [comment]
This is not an issue for hubbit-sniffer, please move further discussion to achieveit
